#ifndef TESTS_H
#define TESTS_H
//Teste Domain
void test_oferta_valida();
void test_oferte_egale();
//Teste Repository
void test_adaugare_oferta();
void test_actualizeaza_oferta();
void test_sterge_oferta();
void test_exista_oferta();
void test_swap_oferte();
//Teste Service
void test_adaugare_oferta_service();
void test_actualizare_oferta_service();
void test_sterge_oferta_service();
void test_ordonare_oferte();
void test_filtrare_oferte();
#endif //TESTS_H
