CREATE TABLE Airplanes (
                           AirplaneID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           Model VARCHAR(100),
                           Capacity INT
);

CREATE TABLE Airports (
                          AirportID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          Name VARCHAR(100),
                          City VARCHAR(100),
                          Country VARCHAR(100)
);

CREATE TABLE Flights (
                         FlightID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         AirplaneID INT REFERENCES Airplanes(AirplaneID) ON DELETE CASCADE,
                         DepartureAirportID INT REFERENCES Airports(AirportID) ON DELETE CASCADE,
                         ArrivalAirportID INT REFERENCES Airports(AirportID) ON DELETE CASCADE,
                         DepartureDateTime TIMESTAMP,
                         ArrivalDateTime TIMESTAMP
);

INSERT INTO Airplanes (Model, Capacity) VALUES
                                            ('Boeing 737', 180),
                                            ('Airbus A320', 150),
                                            ('Embraer E195', 120);

INSERT INTO Airports (Name, City, Country) VALUES
                                               ('Henri Coandă', 'București', 'Romania'),
                                               ('Cluj Internațional', 'Cluj-Napoca', 'Romania'),
                                               ('Heathrow', 'London', 'United Kingdom');

INSERT INTO Flights (AirplaneID, DepartureAirportID, ArrivalAirportID, DepartureDateTime, ArrivalDateTime) VALUES
                                                                                                               (1, 2, 1, '2026-03-01 14:30:00', '2026-03-01 16:50:00'),
                                                                                                               (2, 1, 2, '2026-03-02 09:15:00', '2026-03-02 11:30:00'),
                                                                                                               (3, 3, 1, '2026-03-03 21:45:00', '2026-03-04 00:15:00');