spring.application.name=liquibase

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.queries=DEBUG

# Batching (Cerinta 5)
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true

# HikariCP Settings
# Dimensiunea pool-ului bazata pe formula: connections = (core_count * 2) + effective_spindle_count
spring.datasource.hikari.maximum-pool-size=17
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# Interogare de validare (verifica daca conexiunea mai exista)
spring.datasource.hikari.connection-test-query=SELECT 1

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

logging.file.name=logs/application.log